version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-west-2 --no-include-email)
      - REPOSITORY_URI=XXXXXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/Microservice_A
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Check the current task definition revision
      - TD_REVISION=$(aws ecs describe-services --cluster my-ecs-cluster --service Microservice_A \
        --query "services[].taskDefinition" | jq -r ".[0]")
      - echo Current running task definition revision - $TD_REVISION
      - echo Update Microservice_A
      - cat buildspec/task_definitions/task_definition_dev.json
      - sed -i "s|docker_image|$REPOSITORY_URI:$IMAGE_TAG|g" buildspec/task_definitions/task_definition_dev.json
      - cat buildspec/taskdefinitions/task_definition_dev.json
      - ARN=$(aws ecs register-task-definition --cli-input-json file://buildspec/task_definitions/task_definition_dev.json | jq -r .taskDefinition.taskDefinitionArn)
      - echo $ARN
      - aws ecs update-service --cluster "my-ecs-cluster" --service "Microservice_A" --task-definition $ARN
      - echo List the task definition revisions after the update
      - TD_REVISION=$(aws ecs describe-services --cluster my-ecs-cluster --service Microservice_A \
        --query "services[].taskDefinition" | jq -r ".[0]")
      - echo Task definition running after the update - $TD_REVISION
      - echo Check micorservice version
      - VERSION=$(curl -s http://load_balancer_FQDN:PORT/API_ENDPOINT) #this is for demo purpose
      - echo Microservice_A running version - $VERSION
