- name: Restart postgre
  systemd:
    name: postgresql-10
    state: restarted
    enabled: yes

- name: Restart sonarqube
  systemd:
    name: sonarqube
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes